[package]
name = "spaze-client"
description = "Spaze TUI client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[[bin]]
name = "spaze"
path = "src/main.rs"

[dependencies]
spaze-proto = { path = "../spaze-proto" }
